version: '3.7'
services:
  tfserver:
    image: tensorflow/serving:latest-gpu
    hostname: tfserver
    container_name: tfserver
    restart: always
    networks:
      - inference
    ports:
      - "8500:8500"
      - "8501:8501"
    environment:
      MODEL_NAME: "tracknet"
    volumes:
      - models:/models/


#! VOLUMES
volumes:
  models:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,rw,nolock,soft"
      device: ":/InferenceServerModels/TFServing/models"


#! NETWORK
networks:
  inference:
    driver: bridge
#yeni
#yeni2
#yeni3
#yeni4